### ISSUE TITLE
Missing image pencil.img

### ISSUE THREAD

**Issue by leamas** [rgleason/route_pi#4]
The file _manual/modules/ROOT/pages/great_circle_sailing.adoc_ contains a reference to _pencil.png_, but that image is not available at all in this plugin:

```
$ git grep pencil.png
manual/modules/ROOT/pages/great_circle_sailing.adoc:image::pencil.png[]
$ find . -name pencil.png
$
```

New antora version detects this (thanks!) and emits proper error messages.

**Comment by rgleason** [comment]
Alec,  I pushed pencil.png up to my remote. I've forgotten, does that now solve it?

**Comment by leamas** [comment]
Yup, fixed. Closing

**Comment by rgleason** [comment]
Thanks
